version: "3.8"
services:
  db:
    image: arm64v8/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    # networks:
    #   - assignment
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # networks:
    #   - assignment
  app:
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 9000:9000
    volumes:
      - .:/app
    depends_on:
      - db
    # networks:
    #   - assignment
# networks:
#   assignment:
#     driver: bridge
